services:
  postgresdb:
    image: postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=gochatdb"
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data